### ISSUE TITLE
Permission to use the code

### ISSUE THREAD

**Issue by hidal00p** [shift09/PointGenerator#1]
Dear @jyc-n!

This is not an issue (from github POV) at all, I am simply using the feature to contact you. 
I would like to kindly ask you for permission to use your Poisson point generator implementation in my code. I need it to develop a pseudo random environment for my simulated robot.
I hope to hear back from you. 

Cheers, 
Anton.

**Comment by jyc-n** [comment]
Hi @hidal00p,

This point generator code was written for learning purposes and is no longer maintained. There is no license associated with this repository -- so you can use it for your project :) Please be aware that bugs may exist in my code, so please use it with caution.

**Comment by hidal00p** [comment]
Yes of course, I am fully aware of that. But it is actually a perfect implementation for me, as I simply need a point generator that I am really lazy to implement myself.
I really appreciate your work, and understanding.

Best,
Anton.
